name: Build App

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build extensions
    if: "!startsWith(github.event.head_commit.message, '[SKIP CI]')"
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone master branch
        uses: actions/checkout@v2
        with:
          ref: master
          path: master

      - name: Set up Kotlin
        uses: fwilhe2/setup-kotlin@main

      - name: Create repo artifacts
        run: |
          cd master
          ./.github/scripts/create-repo.sh
